import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
            <header className="w-full flex items-center justify-between py-4 px-8 bg-gray-800 text-white mb-8">
              <div className="text-xl font-bold">Samuel Tulipano</div>
              <nav>
                <ul className="flex space-x-6">
                  <li><a href="/" className="hover:underline">Home</a></li>
                  <li><a href="/about" className="hover:underline">About</a></li>
                  <li><a href="/escaperoom" className="hover:underline">Escape Room</a></li>
                  <li><a href="/codingraces" className="hover:underline">Coding Races</a></li>
                  <li><a href="/courtroom" className="hover:underline">Court Room</a></li>

                </ul>
              </nav>
            </header>
        {children}
        <footer className="w-full text-center py-4 bg-gray-100 text-gray-700 mt-8">
          © 2025 CWA ASSIGNMENT 1 | Samuel Tulipano | 22298158 | 18/08/2025
        </footer>
      </body>
    </html>
  );
}
